### ISSUE TITLE
Add delay per request parameter

### ISSUE THREAD

**Issue by dimkouv** [dimkouv/massivedl#8]
Add a new command line parameter for defining a delay in seconds (float) per request.

**Comment by badmotherbutter** [comment]
Hi @dimkouv! 
If you don't mind I'll try to complete this enhancement.
My understanding is that you want an additional command line parameter which defines the delay between each request start time.
e.g. massivedl_darwin_amd64 -i examples/list-of-photos.csv -D 1.5

Request1 will start at T1
Request2 will start at T1+1.5s (aka T2)
Request3 will start at T2+1.5s (aka T3)

Is is correct?

Thank you

**Comment by dimkouv** [comment]
@badmotherbutter thank you!

Correct but when you're having parallel requests (2 for example) then
```
req1 @ t1
req2 @ t1
req3 @ t1 + d
req4 @ t1 + d
```

You can parse the cmdline param `-d` and call time.Sleep on every request.

-- p.s. You can also update `Makefile` for your mac's architecture ^_^

**Comment by badmotherbutter** [comment]
Perfect thank you! :)
